#!/bin/env bash
#./xrankmirrors -g -c
SELECTED=$(echo $(./xrankmirrors -f | fzf --layout=reverse --header-lines=3) | awk -F' ' '{ print $1 }')
#FILTERED=$(awk -F ' ' '{ print $1 }')

echo $SELECTED
exit 0
